# Site wide configuration

title:            Rizki Mufrizal
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Rizki Mufrizal
  avatar: RizkiMufrizal.jpg
  bio: "Mahasiswa Teknik Informatika di Universitas Gunadarma. Aktif Mengikuti perkembangan Teknologi open source
  terutama di bidang pemrograman Java, Javascript dan Linux"
  email: mufrizalrizki@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: rizkimufrizal
  google:
    plus: rizkimufrizal
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify: B56E20F17096917513DB6E5ADF9AB9AC
  github: RizkiMufrizal
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: RizkiMufrizal
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
